	;; Assembly code generated by Chao Compiler.
	;; Use aslc86k to assemble this.

	.include "sfr.i"

main2:
	pop $0
	pop $1
	mov #$0, acc
	add 5
	st $0
	mov #10, acc
	push acc
	ret

main:
	mov #50, acc
	st $2
	mov #50, acc
	st $52
	mov #$52, acc
	st $3
	push $3
	push $2
	call main2
